#!/bin/bash
# 1. Randomize password of postgres autogenerated user
# sudo passwd postgres
# 2. Access to PostgreSQL command line
# 3. Create the new super user for Resource with all the permissions
# 4. Create the database for Resource
# NOTICE that creating a database takes about 30s.
sudo -u postgres psql <<EOF
CREATE USER nublic_resource WITH 
      SUPERUSER
      PASSWORD 'ScamUp';
CREATE DATABASE nublic_resource WITH OWNER nublic_resource
    ENCODING 'UTF8';
EOF
# Similar in the shell is: createuser -s -P -U usuario nublic_resource