all:
	echo "Make nothing"

install:
	mkdir -p ${DESTDIR}/etc/tomcat6
	cp catalina.properties ${DESTDIR}/etc/tomcat6
	cp server.xml ${DESTDIR}/etc/tomcat6
	mkdir -p ${DESTDIR}/etc/init.d
	cp tomcat6 ${DESTDIR}/etc/init.d
