package com.scamall.app.image;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

/**
 * 
 * @author Elena Vielva
 *
 */
public class ImageMainComponent extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout;

	@AutoGenerated
	private VerticalLayout sidebarLayout;

	@AutoGenerated
	private VerticalLayout actionLayout;

	@AutoGenerated
	private Panel searchPanel;

	@AutoGenerated
	private VerticalLayout navigationImageLayout;

	@AutoGenerated
	private Panel navigation;

	
	private Embedded image;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5603069891648148067L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ImageMainComponent() {
		buildMainLayout();
		setCompositionRoot(horizontalLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout
		horizontalLayout = buildHorizontalLayout();
		horizontalLayout.setWidth("-1px");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setImmediate(false);
		mainLayout.addComponent(horizontalLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		horizontalLayout = new HorizontalLayout();
		
		// navigationImageLayout
		navigationImageLayout = buildNavigationImageLayout();
		navigationImageLayout.setWidth("70.0%");
		navigationImageLayout.setHeight("-1px");
		navigationImageLayout.setImmediate(false);
		horizontalLayout.addComponent(navigationImageLayout);
		
		// sidebarLayout
		sidebarLayout = buildSidebarLayout();
		sidebarLayout.setWidth("30.0%");
		sidebarLayout.setHeight("-1px");
		sidebarLayout.setImmediate(false);
		horizontalLayout.addComponent(sidebarLayout);
		
		return horizontalLayout;
	}

	@AutoGenerated
	private VerticalLayout buildNavigationImageLayout() {
		// common part: create layout
		navigationImageLayout = new VerticalLayout();
		
		// navigation
		navigation = new Panel();
		navigation.setWidth("100.0%");
		navigation.setHeight("-1px");
		navigation.setImmediate(false);
		navigationImageLayout.addComponent(navigation);
		
		// Image
		image = new Embedded();
		image.setWidth("100%");
		image.setHeight("-1px");
		image.setCaption("Prueba");
		image.setSource(new ExternalResource("http://tecmoviles.com/wp-content/uploads/pinky-cerebro-google-en-thumb.jpg"));
		navigationImageLayout.addComponent(image);
		
		// NameDate
		Label NameDate = new Label();
		NameDate.setWidth("100.0%");
		NameDate.setHeight("-1px");
		NameDate.setCaption("Titulo");
		NameDate.setImmediate(false);
		NameDate.setValue("12");
		navigationImageLayout.addComponent(NameDate);
		
		return navigationImageLayout;
	}

	@AutoGenerated
	private VerticalLayout buildSidebarLayout() {
		// common part: create layout
		sidebarLayout = new VerticalLayout();
		
		// searchPanel
		searchPanel = new Panel();
		searchPanel.setWidth("100.0%");
		searchPanel.setHeight("-1px");
		searchPanel.setImmediate(false);
		sidebarLayout.addComponent(searchPanel);
		
		// actionLayout
		actionLayout = new VerticalLayout();
		actionLayout.setWidth("100.0%");
		actionLayout.setHeight("-1px");
		actionLayout.setImmediate(false);
		sidebarLayout.addComponent(actionLayout);
		sidebarLayout.setComponentAlignment(actionLayout, new Alignment(48));
		
		return sidebarLayout;
	}

}
