#!/usr/bin/python

from nublic_app_market_daemon.apt_daemon import *
from dbus.mainloop.glib import DBusGMainLoop

from rpcbd import ThreadedTCPJsonRpcPeer, JSONRPC_V2
import dbus
import gobject
import time

if __name__ == '__main__':
    # Initialize JSON-RPC
    logging.basicConfig(level = logging.WARNING)
    peer = ThreadedTCPJsonRpcPeer(JSONRPC_V2, default_handler = Apt)
    peer.listen_tcp(port = 5442)
    
    # Initialize D-Bus loop
    dbus_loop = DBusGMainLoop(set_as_default=True)
    # Initialize D-Bus objects
    apt = Apt(dbus_loop)
    # Start GObject loop
    loop = gobject.MainLoop()
    gobject.threads_init()
    loop.run()
