#!/usr/bin/python

#from nublic_files_and_users_client.dbus_client import *
#from nublic_files_and_users_client.utf8 import *
import sys

from nublic.files_and_users.mirror import *

if __name__ == '__main__':
    # Add a mirror
    if sys.argv[1] == 'create':
        sys.stdout.write("Name to be shown: ")
        name = sys.stdin.readline().strip()
        sys.stdout.write("Owner: ")
        owner = sys.stdin.readline().strip()
        mid = create_mirror(to_utf8(name), to_utf8(owner))
        sys.stdout.write("Mirror created with id ")
        sys.stdout.write(str(mid))
        sys.stdout.write("\n")
    # Delete a mirror
    elif sys.argv[1] == 'delete':
        mid = sys.argv[2]
        Mirror(int(mid)).delete()
        sys.stdout.write("Mirror deleted\n")
    # List mirror
    elif sys.argv[1] == 'list':
        for mirror in get_all_mirrors():
            sys.stdout.write(str(mirror))
            sys.stdout.write("\n")
