#!/usr/bin/python

#from nublic_files_and_users_client.dbus_client import *
#from nublic_files_and_users_client.utf8 import *
import sys

from nublic.files_and_users.work_folder import *

if __name__ == '__main__':
    # Add a synced folder
    if sys.argv[1] == 'create':
        sys.stdout.write("Name to be shown: ")
        name = sys.stdin.readline().strip()
        sys.stdout.write("Owner: ")
        owner = sys.stdin.readline().strip()
        mid = create_work_folder(to_utf8(name), to_utf8(owner))
        sys.stdout.write("Work folder created with id ")
        sys.stdout.write(str(mid))
        sys.stdout.write("\n")
    # Delete a synced folder
    elif sys.argv[1] == 'delete':
        mid = sys.argv[2]
        WorkFolder(int(mid)).delete(False)
        sys.stdout.write("Work folder deleted\n")
    # List symced folders
    elif sys.argv[1] == 'list':
        for wf in get_all_work_folders():
            sys.stdout.write(str(wf))
            sys.stdout.write("\n")
