#!/usr/bin/python

from nublic_files_and_users_client.dbus_client import *
from nublic_files_and_users_client.utf8 import *
import sys

if __name__ == '__main__':
    # Add a synced folder
    if sys.argv[1] == 'create':
        sys.stdout.write("Name to be shown: ")
        name = sys.stdin.readline().strip()
        sys.stdout.write("Owner: ")
        owner = sys.stdin.readline().strip()
        mid = create_synced_folder(to_utf8(name), to_utf8(owner))
        sys.stdout.write("Synced folder created with id ")
        sys.stdout.write(str(mid))
        sys.stdout.write("\n")
    # Delete a synced folder
    elif sys.argv[1] == 'delete':
        mid = sys.argv[2]
        delete_synced_folder(int(mid))
        sys.stdout.write("Synced folder deleted\n")
    # List symced folders
    elif sys.argv[1] == 'list':
        for mirror in list_synced_folders():
            sys.stdout.write(str(mirror))
            sys.stdout.write("\n")
