#!/bin/bash -e
mv /etc/samba/smb.conf /etc/samba/smb.conf.backup || true
ln -s /var/lib/nublic/smb.conf /etc/samba/smb.conf
#ufw enable netbios-ns
ufw allow netbios-ns
#ufw enable netbios-dgm
ufw allow netbios-dgm
#ufw enable netbios-ssn
ufw allow netbios-ssn
#ufw enable microsoft-ds
ufw allow microsoft-ds
# ufw enable ldap # Not needed right now
# ufw enable swat # If we want to allow Samba Web Administration Tool
ufw --force enable
service smbd restart
