all:
	echo "Make nothing"

install:
	mkdir -p ${DESTDIR}/var/lib/nublic/apps
	cp music.json ${DESTDIR}/var/lib/nublic/apps
	mkdir -p ${DESTDIR}/var/lib/nublic/app-images
	cp music.png ${DESTDIR}/var/lib/nublic/app-images
