#!/usr/bin/python
'''
Created on 10/08/2010

It works for usage during the install of applications.

@author: David Navarro Estruch
@copyright: 2011 Nublic
'''
import os
import sys
from optparse import OptionParser

from nublic_resource.select_provider import generate_provider, get_provider
from nublic_resource.database_stored import ExistingKeyError

CONFIG_DIR = '/etc/nublic'


def main():
    if not os.geteuid() == 0:
        sys.exit('nublic-resource-setup must be run as root')
    usage = "usage: \n" + \
            "\t%prog install app_id key_name resource [[-o optional_arg]]\n" + \
            "\t%prog request app_id key_name [[-o optional_arg]]\n" + \
            "\t%prog uninstall app_id key_name\n" + \
            "\t%prog release app_id key_name\n" + \
            "\t%prog value   app_id key_name#subkey \n" + \
            "\n" + \
            "Optional args:\n" + \
            "\t-o --optional_arg: Provides a optional_arg"
    parser = OptionParser(usage)
    parser.add_option("-o", "--optional-args", action="append",
                      type="string", dest="optional")
    (options, args) = parser.parse_args()

    if len(args) == 0:
        parser.error("Invalid order")

    if args[0] == 'install':
        if len(args) != 4:
            parser.error("Invalid number of parameters")
        app = args[1]
        key = args[2]
        # TODO Chech if the app + key are already used
        resource_id = args[3]
        provider = generate_provider(resource_id)
        if provider is None:
            parser.error("Invalid resource")
        try:
            provider.install(app, key)
        except ExistingKeyError:
            print "Existing Database for %s with key %s" % (app, key)
        # Write configuration file
        path = os.path.join(CONFIG_DIR, '%s_%s.%s' % (app, key, "cfg"))
        with open(path, 'w') as f:
            header = "[%s_%s]" % (app, key)
            uri = provider.value(app, key, 'uri')
            config_line = "%s_%s_uri = %s" % (app, key, uri)
            config_sqlalchemy = "SQLALCHEMY_DATABASE_URI = %s" % (uri)
            f.write(header + '\n')
            f.write(config_line + '\n')
            f.write(config_sqlalchemy + '\n')

    elif args[0] == 'uninstall':
        if len(args) != 3:
            parser.error("Invalid number of parameters")
        app = args[1]
        key = args[2]
        provider = get_provider(app, key)
        if provider is None:
            parser.error("Invalid resource")
        provider.uninstall(app, key)
        path = os.path.join(CONFIG_DIR, '%s_%s' % (app, key), ".cfg")
        os.remove(path)

    elif args[0] == 'request':
        if len(args) != 4:
            parser.error("Invalid number of parameters")
        app = args[1]
        key = args[2]
        resource_id = args[3]
        provider = generate_provider(resource_id)
        if provider is None:
            parser.error("Invalid resource")
        provider.request(app, key)
    elif args[0] == 'release':
        if len(args) != 3:
            parser.error("Invalid number of parameters")
        app = args[1]
        key = args[2]
        provider = get_provider(app, key)
        if provider is None:
            parser.error("Invalid resource")
        provider.release(app, key)
    elif args[0] == 'value':
        if len(args) != 3:
            parser.error("Invalid number of parameters")
        app = args[1]
        key_subkey = args[2]
        key, separator, subkey = key_subkey.partition("#")
        provider = get_provider(app, key)
        if separator != "/":  # Doesn't have a subkey value
            parser.error("subkey not specified")
        else:
            print(provider.value(app, key, subkey))
    else:
        parser.error("Invalid order")

if __name__ == '__main__':
    main()
