all:
	echo "Make nothing"

install:
	mkdir -p ${DESTDIR}/etc/tomcat7
	cp catalina.properties ${DESTDIR}/etc/tomcat7
	cp server.xml ${DESTDIR}/etc/tomcat7
	mkdir -p ${DESTDIR}/etc/init.d
	cp tomcat7 ${DESTDIR}/etc/init.d
