#!/bin/sh

# Change fstab file
set-acls.py
# Remount the root
mount -o remount /
# Set jetty to be able to write everywhere
for dir in cache fs log work-folders "data/nublic-only" "data/mirrors" "data/work-folders"
do
    CURRENT_DIR=/var/nublic/${dir}
    setfacl -Rdm u:jetty:rwx ${CURRENT_DIR}
    setfacl -Rdm u:www-data:rwx ${CURRENT_DIR}
done
# Set jetty to be able to read apps configurations
setfacl -Rdm u:jetty:rx /var/lib/nublic/apps
# Allow jetty to write logs
mkdir -p /var/log/nublic
setfacl -Rdm u:jetty:rwx /var/log/nublic
chmod 777 /var/log/nublic
# Set OpenJDK 7 as default virtual machine
update-java-alternatives -s java-1.7.0-openjdk-\*
# Set ubuntu firewall
ufw default deny
# Enable SSH access from ufw in case openssh config is not installed
ufw allow OpenSSH

ufw --force enable
