#!/usr/bin/python

# Runs in the foreground. It is suited for use with the Upstart manager

# Initial version from: http://www.python.org/dev/peps/pep-3143/ from Public Domain
# Second version from: https://gist.github.com/339430
#
# @author: David Navarro Estruch
# @author: Alejandro Serrano Mena
# @copyright: 2011 Nublic


from nublic_file_watcher.preview_queue import CentralQueue
from nublic_file_watcher.preview_processor import Element
from nublic.filewatcher import Processor, init_watcher

from photo_processor import PhotoProcessor

from time import sleep
import logging
import signal

class MainProcessor(Processor):
    def __init__(self, watcher, logger):
        Processor.__init__(self, "previewer", watcher, False)
        self.central_queue = CentralQueue.start([PhotoProcessor()])

    def process(self, change):
        self.central_queue.tell(('_watcher', Element(change)))

if __name__ == '__main__':
    logging.basicConfig(level = logging.WARNING)
    init_socket_watcher("previewer",[MainProcessor.start()])

    try:
        while True:
            sleep(1)
    except KeyboardInterrupt:
        peer.shutdown()
    sys.stderr.write("Resource daemon shutdown\n")
