#!/usr/bin/python

# Runs in the foreground. It is suited for use with the Upstart manager

# Initial version from: http://www.python.org/dev/peps/pep-3143/ from Public Domain
# Second version from: https://gist.github.com/339430
#
# @author: David Navarro Estruch
# @copyright: Nublic

import os
import logging

from dbus_handler import (
    initial_program_setup,
    do_main_program,
    program_cleanup,
    reload_program_config,
    )

if __name__ == '__main__':
    initial_program_setup()
    do_main_program()
    program_cleanup()

