all:
	echo "Make nothing"

install:
	mkdir -p ${DESTDIR}/var/lib/nublic/apps
	cp browser.json ${DESTDIR}/var/lib/nublic/apps
	mkdir -p ${DESTDIR}/var/lib/nublic/app-images
	cp browser.png ${DESTDIR}/var/lib/nublic/app-images
