#!/bin/bash -e
# Add database
nublic-resource-setup install nublic_files_and_users db postgresql-db
service nublic-files-and-users start
# Create storage for Apache configuration files
mkdir -p /var/nublic/secure
setfacl -Rdm u:nublic:rwx /var/nublic/secure
